import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providres from "@/providers";
import { Toaster } from "sonner";
import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Dashboard Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providres>
      <html suppressHydrationWarning lang="en">
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <div className="flex h-screen overflow-hidden">
              <aside className="w-[250px] h-full sticky top-0 left-0 overflow-y-auto">
                <Sidebar />
              </aside>

              <div className="flex-1 flex flex-col overflow-y-auto">
                <header className="sticky top-0 z-10 bg-background">
                  <Header />
                </header>
                <main className="flex-1 p-4">{children}</main>
              </div>
            </div>
            <Toaster position="top-center" />
          </ThemeProvider>
        </body>
      </html>
    </Providres>
  );
}
