import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providres from "@/providers";
import { Toaster } from "sonner";
import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Dashboard Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providres>
      <html suppressHydrationWarning lang="en">
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <main className="flex">
              <Sidebar />
              <div className="w-full mx-auto flex flex-col">
                <Header />
                {children}
              </div>
            </main>
            <Toaster position="top-center" />
          </ThemeProvider>
        </body>
      </html>
    </Providres>
  );
}
