import type { ChildrenType } from "@/@types";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providres from "@/providers";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Admin Crm Login",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: ChildrenType) => {
  return (
    <Providres>
      <html suppressHydrationWarning={true} lang="en">
        <body className={`${inter.className} antialiased`}>
          {children} <Toaster position="top-center" />
        </body>
      </html>
    </Providres>
  );
};

export default AuthLayout;
